# Generated by Django 3.1.3 on 2021-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='data/')),
            ],
        ),
    ]
